---
abstract: 'Assert that your Perl files compile OK.'
author:
  - 'Evan Giles <egiles@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Compile
provides:
  Test::Compile:
    file: lib/Test/Compile.pm
    version: v3.0.1
  Test::Compile::Internal:
    file: lib/Test/Compile/Internal.pm
    version: v3.0.1
requires:
  Exporter: '5.68'
  parent: '0.225'
  perl: v5.10.0
  version: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/egiles/test-compile
version: v3.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
